runtime: nodejs
env: flex
service: dbonecloudsql
# [START cloudsql_settings]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: lpsync:us-central1:lpsync-db
# [END cloudsql_settings]
# [END app_yaml]